# Generated by Django 2.1.1 on 2018-09-11 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=15)),
                ('dob', models.DateField(max_length=8)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='rentby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.person'),
        ),
    ]
